---
version: '3.5'
services:

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - zookeeper0
      - kafka0
    environment:
      KAFKA_CLUSTERS_0_NAME: hw3_cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper0:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8085
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083
      KAFKA_CLUSTERS_0_KSQLDBSERVER: http://ksqldb:8088
  zookeeper0:
    image: confluentinc/cp-zookeeper:5.5.9
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SNAPSHOT_TRUST_EMPTY: "true"
    ports:
      - 2181:2181
    volumes:
      - ./data/zookeeper-data:/var/lib/zookeeper/data
      - ./data/zookeeper-logs:/var/lib/zookeeper/log

  kafka0:
    image: confluentinc/cp-enterprise-kafka:5.5.9
    depends_on:
      - zookeeper0
    ports:
      - 9092:9092
      - 9997:9997
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KSQL_KSQL_STREAMS_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"      
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.j1mxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9997

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - kafka0
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka0:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka0:29092 --create --if-not-exists --topic my-topic-1 --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka0:29092 --create --if-not-exists --topic my-topic-2 --replication-factor 1 --partitions 1
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-event
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-creation
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-update
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-revert-action
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-creation-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-update-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-revert-action-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic user-activities-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-activities-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-creation-hourly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-update-hourly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-revert-action-hourly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic user-activities-hourly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-activities-hourly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-creation-daily-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-update-daily-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-revert-action-daily-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic user-activities-daily-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-activities-daily-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-creation-weekly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-update-weekly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-revert-action-weekly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic user-activities-weekly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-activities-weekly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-creation-monthly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-update-monthly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-revert-action-monthly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic user-activities-monthly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-activities-monthly-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-creation-bots-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-update-bots-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-revert-action-bots-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic user-activities-bots-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-activities-bots-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-creation-none-bots-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-update-none-bots-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-revert-action-none-bots-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic user-activities-none-bots-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-activities-none-bots-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-creation-language-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-update-language-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-revert-action-language-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic user-activities-language-count
      kafka-topics --create --if-not-exists --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 --topic page-activities-language-count

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka0:29092 --list
      "